import Head from "next/head";
import Footer from "@/components/Footer";
import ErrorPage from "@/components/ErrorPage";
import {getFooterMenuLinks} from "../lib/MenuLinks";
import {getThemesOptionsContent} from "../lib/themesOptions";

const noPageExits = ({footerMenuLinks, themesOptionsContent}: any) => {
	return (
		<>
			<Head>
				<title>404 Page Not Found | Prime Apartments</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/img/Logo.png" />
			</Head>

			<main>
				<ErrorPage
					title={themesOptionsContent?.errorPageContent?.title}
					paragraph={themesOptionsContent?.errorPageContent?.paragraph}
					buttonLink={themesOptionsContent?.errorPageContent?.buttonLink}
					backgroundImage={
						themesOptionsContent?.errorPageContent?.backgroundImage?.sourceUrl
					}
				/>

				<Footer
					email={themesOptionsContent?.email}
					emailTwo={themesOptionsContent?.emailTwo}
					phoneNumber={themesOptionsContent?.phoneNumber}
					twitterLink={themesOptionsContent?.twitterLink}
					facebookLink={themesOptionsContent?.facebookLink}
					linkedinLink={themesOptionsContent?.linkedinLink}
					footerMenuLinks={footerMenuLinks?.footerMenuLinks}
					copyRightText={themesOptionsContent?.copyrightText}
					phoneNumberTwo={themesOptionsContent?.phoneNumberTwo}
				/>
			</main>
		</>
	);
};

export default noPageExits;

export async function getStaticProps() {
	const footerMenuLinks: object = await getFooterMenuLinks();
	const themesOptionsContent: object = await getThemesOptionsContent();

	return {
		props: {
			footerMenuLinks,
			themesOptionsContent,
		},
		revalidate: 60,
	};
}
