import Head from "next/head";
import {motion} from "framer-motion";
import type {NextPage, GetStaticProps} from "next";
import {getFooterMenuLinks} from "../functions/MenuLinks";
import {getThemesOptionsContent} from "../functions/themesOptions";

// Components
import Footer from "@/components/Footer";
import ErrorPage from "@/components/ErrorPage";

interface INoPageExits {
	footerMenuLinks: {
		footerMenuLinks: [
			{
				node: {
					id: string;
					url: string;
					label: string;
				};
			}
		];
	};
	themesOptionsContent: {
		email: string;
		emailTwo: string;
		phoneNumber: string;
		phoneNumberTwo: string;
		twitterLink: string;
		facebookLink: string;
		linkedinLink: string;
		copyRightText: string;
		errorPageContent: {
			title: string;
			paragraph: string;
			buttonLink: {
				url: string;
				title: string;
				target: string;
			};
			backgroundImage: {
				sourceUrl: string;
			};
		};
	};
}

const noPageExits: NextPage<INoPageExits> = ({
	footerMenuLinks,
	themesOptionsContent,
}) => {
	return (
		<motion.div
			exit={{
				opacity: 0,
			}}
			initial="initial"
			animate="animate"
		>
			<Head>
				<title>404 Page Not Found | Prime Apartments</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/img/Logo.png" />
			</Head>

			<main>
				<ErrorPage
					title={themesOptionsContent?.errorPageContent?.title}
					paragraph={themesOptionsContent?.errorPageContent?.paragraph}
					buttonLink={themesOptionsContent?.errorPageContent?.buttonLink}
					backgroundImage={
						themesOptionsContent?.errorPageContent?.backgroundImage?.sourceUrl
					}
				/>

				<Footer
					email={themesOptionsContent?.email}
					emailTwo={themesOptionsContent?.emailTwo}
					phoneNumber={themesOptionsContent?.phoneNumber}
					twitterLink={themesOptionsContent?.twitterLink}
					facebookLink={themesOptionsContent?.facebookLink}
					linkedinLink={themesOptionsContent?.linkedinLink}
					footerMenuLinks={footerMenuLinks?.footerMenuLinks}
					copyRightText={themesOptionsContent?.copyRightText}
					phoneNumberTwo={themesOptionsContent?.phoneNumberTwo}
				/>
			</main>
		</motion.div>
	);
};

export default noPageExits;

export const getStaticProps: GetStaticProps = async () => {
	const footerMenuLinks: object = await getFooterMenuLinks();
	const themesOptionsContent: object = await getThemesOptionsContent();

	return {
		props: {
			footerMenuLinks,
			themesOptionsContent,
		},
		revalidate: 60,
	};
};
